FROM ubuntu:20.04
RUN apt-get -y update 
RUN apt-get -y install software-properties-common 
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get -y install python3.9
RUN apt-get -y install python3-pip
RUN apt-get -y install nano
RUN apt install net-tools
RUN apt-get -y install iproute
